---
- name: redhat | installing epel repo (RedHat)
  yum:
    name: epel-release
    state: present
  become: true

- name: redhat | Installing NGINX
  yum:
    name: nginx
    state: present
  become: true
    
- name: redhat | ensuring nginx is started and enabled on boot
  service:
    name: nginx
    state: started
    enabled: yes
  become: true
...